package com.example.PostgreSQLDataBaseConnect.repositories;

// import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;
// import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
// import org.springframework.test.context.junit.jupiter.SpringExtension;

import com.example.PostgreSQLDataBaseConnect.TestDataUtil;
import com.example.PostgreSQLDataBaseConnect.domain.entities.AuthorEntity;
import com.example.PostgreSQLDataBaseConnect.respositories.AuthorRepository;

@SpringBootTest
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class AuthorRepositoryIntegrationTests {

    private AuthorRepository underTest; // reference to our class

    // AUTOWIRED BASICALLY SAYS TO SPRINGBOOT TO INJECT DEPENDENCIES AS DECLARED IN THIS CONSTRUCTOR OF DAO
    @Autowired
    public AuthorRepositoryIntegrationTests(AuthorRepository underTest) {
        this.underTest = underTest;
    }

    // test to see if we can create an author and find it using the findOne method
    @Test
    public void testThatAuthorCanBeCreatedAndRecalled() {

        AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
        
        underTest.save(author);
        
        Optional<AuthorEntity> result = underTest.findById(author.getId());
        assertThat(result).isPresent();
        assertThat(result.get()).isEqualTo(author);
    }

    @Test
    public void testThatMultipleAuthorsCanBeCreatedAndRecalled() {
        // initializing authors
        AuthorEntity authorA = TestDataUtil.createTestAuthorEntityA();
        // creating these authors in our DB
        underTest.save(authorA);

        AuthorEntity authorB = TestDataUtil.createTestAuthorB();
        underTest.save(authorB);

        AuthorEntity authorC = TestDataUtil.createTestAuthorC();
        underTest.save(authorC);

        Iterable<AuthorEntity> result = underTest.findAll();
        assertThat(result).hasSize(3).
                          contains(authorA, authorB, authorC);

    }

    @Test
    public void testThatAuthorCanBeUpdated() {
        AuthorEntity authorA = TestDataUtil.createTestAuthorEntityA();
        underTest.save(authorA);

        authorA.setName("UPDATED");

        // ".save()" is used for both creating and updating an object in a DB
        underTest.save(authorA);

        Optional<AuthorEntity> result = underTest.findById(authorA.getId());

        assertThat(result).isPresent();
        assertThat(result.get()).isEqualTo(authorA);
    }

    @Test
    public void testThatAuthorCanBeDeleted() {
        AuthorEntity author = TestDataUtil.createTestAuthorEntityA();
        underTest.save(author);

        underTest.deleteById(author.getId());

        Optional<AuthorEntity> result = underTest.findById(author.getId());

        assertThat(result).isEmpty();
    }

    @Test
    public void testThatGetAuthorsWithAgeLessThan() {
        AuthorEntity testAuthorA = TestDataUtil.createTestAuthorEntityA();
        underTest.save(testAuthorA);

        AuthorEntity testAuthorB = TestDataUtil.createTestAuthorB();
        underTest.save(testAuthorB);

        AuthorEntity testAuthorC = TestDataUtil.createTestAuthorC();
        underTest.save(testAuthorC);

        // this method is auto-generated by springdata jpa
        Iterable<AuthorEntity> result = underTest.findByAgeLessThan(50);
        assertThat(result).containsExactly(testAuthorB, testAuthorC);
    }

    @Test
    public void testThatGetAuthorsWithAgeGreaterThan() {
        AuthorEntity testAuthorA = TestDataUtil.createTestAuthorEntityA();
        underTest.save(testAuthorA);

        AuthorEntity testAuthorB = TestDataUtil.createTestAuthorB();
        underTest.save(testAuthorB);

        AuthorEntity testAuthorC = TestDataUtil.createTestAuthorC();
        underTest.save(testAuthorC);

        // purposefully giving a difficult to figure out method name
        // to see what does spring jpa do when confused of which query needs to be executed
        Iterable<AuthorEntity> result = underTest.findAuthorsWithAgeGreaterThan(50);
        assertThat(result).containsExactly(testAuthorA);
    }
}
